name: Build and Deploy
on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - run: npm run generate
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project wanyu-app
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
